# Test configuration for rapid mode feature
genome_id: "test_genome_v1"
genome: "/path/to/test/genome.fa"
outdir: "results"
rapid_mode: true

samples: 
  sample1:
    type: "chipseq"
    R1: "/path/to/sample1_R1.fastq.gz"
    R2: "/path/to/sample1_R2.fastq.gz"
